parameters:
    ## Purge type used by HttpCache system ("local", "varnish"/"http", and on ee also "fastly")
    # env: HTTPCACHE_PURGE_TYPE
    purge_type: local

    # One of `legacy` (default) or `solr`
    search_engine: '%env(SEARCH_ENGINE)%'

    # Settings for Cache pool, to change add own cache service and optionally inject own arguments
    # predefined pools: see symfony config and the optional pools in app/config/cache_pool/
    cache_pool: '%env(CACHE_POOL)%'

    # Settings for HttpCache
    purge_server: '%env(HTTPCACHE_PURGE_SERVER)%'

    # By default cache ttl is set to 24h, when using Varnish you can set a much higher value. High values depends on
    # using EzSystemsPlatformHttpCacheBundle (default as of v1.12) which by design expires affected cache on changes
    httpcache_default_ttl: '%env(HTTPCACHE_DEFAULT_TTL)%'

    # Varnish invalidation/purge token (for use on platform.sh, eZ Platform Cloud and other places you can't use IP for ACL)
    varnish_invalidate_token: '%env(HTTPCACHE_VARNISH_INVALIDATE_TOKEN)%'

    # Solr root endpoint, relevant if `solr` is set as search_engine
    solr_dsn: '%env(SOLR_DSN)%'
    solr_core: '%env(SOLR_CORE)%'

    # collation currently has effect on MySQL only
    database_collation: '%env(DATABASE_COLLATION)%'
    database_charset: '%env(DATABASE_CHARSET)%'


    # Cache namespace prefix for use with Redis/Memcached, 'ez' by default.
    # For further info incl alternatives for "blue/green deployment" and multi repo installs, see: app/config/cache_pool/*.yml
    cache_namespace: '%env(CACHE_NAMESPACE)%'


    ezpublish_rest.csrf_token_intention: authenticate

ezpublish:
    # HttpCache settings, By default 'local' (Symfony HttpCache Proxy), by setting it to 'http' you can point it to Varnish
    http_cache:
        purge_type: '%purge_type%'

    # Repositories configuration, setup default repository to support solr if enabled
    repositories:
        default:
            storage: ~
            search:
                engine: '%search_engine%'
                connection: default

    # Siteaccess configuration, with one siteaccess per default
    siteaccess:
        list: [site]
        groups:
            site_group: [site]
        default_siteaccess: site
        match:
            URIElement: 1

    # System settings, read in following order: `default`, <siteaccess-group>, <siteacces>, and `global`
    # TIP: For multisite installations organize shared config into SiteAccess groups,
    #      on single-site you can place shared config under "default" for simplicity as shown below.
    system:
        default:
            # Cache pool service, needs to be different per repository (database) on multi repository install.
            cache_service_name: '%cache_pool%'
            # These reflect the current installers, complete installation before you change them. For changing var_dir
            # it is recommended to install clean, then change setting before you start adding binary content, otherwise you'll
            # need to manually modify your database data to reflect this to avoid exceptions.
            var_dir: var/site
            content:
                # As we by default enable EzSystemsPlatformHttpCacheBundle which is designed to expire all affected cache
                # on changes, and as error / redirects now have separate ttl, we easier allow ttl to be greatly increased
                default_ttl: '%httpcache_default_ttl%'
            # HttpCache purge server(s) setting, eg Varnish, for when ezpublish.http_cache.purge_type is set to 'http'.
            http_cache:
                purge_servers: ['%purge_server%']
#                varnish_invalidate_token: '%varnish_invalidate_token%' # @todo fix

        #site_group:
        #    design: main

        site:
            languages: [eng-GB]

    url_alias:
        slug_converter:
            transformation: 'urlalias_lowercase'

#ez_platform_standard_design:
#    # makes Kernel default templates (in EzPublishCoreBundle/Resources/views) part of standard Design
#    override_kernel_templates: true

# If you are not using MySQL, you can comment-out this section
ez_doctrine_schema:
    tables:
        options:
            charset: '%database_charset%'
            collate: '%database_collation%'

# Base configuration for Solr, for more options see: https://doc.ezplatform.com/en/latest/guide/search/#solr-bundle
# Can have several connections used by each eZ Repositories in ezplatform.yml
#ez_search_engine_solr:
#    endpoints:
#        endpoint0:
#            dsn: '%solr_dsn%'
#            core: '%solr_core%'
#    connections:
#        default:
#            entry_endpoints:
#                - endpoint0
#            mapping:
#                default: endpoint0
