parameters:
    # Admin siteaccess group name
    admin_group_name: admin_group

ezpublish:
    siteaccess:
        list: [admin]
        groups:
            # WARNING: Do not remove or rename this group.
            # It's used to distinguish common siteaccesses from admin ones.
            # In case of multisite with multiple admin panels, remember to add any additional admin siteaccess to this group.
            admin_group: [admin]

    system:
        admin_group:
            # For admin this needs to contain all languages you want to translate content to on the given repository.
            languages: [eng-GB]
            content_tree_module:
                contextual_tree_root_location_ids:
                    - 2 # Home (Content structure)
                    - 5 # Users
                    - 43 # Media
                    - 48 # Setup

framework:
    translator: { fallback: '%locale_fallback%' }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    validation: { enable_annotations: true }
    default_locale: '%locale_fallback%'
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        # if handler_id set to null will use default session handler from php.ini
        handler_id: '%ezplatform.session.handler_id%'
        save_path: '%ezplatform.session.save_path%'
        # Note: eZ Platform also allows session name and session cookie configuration to be per SiteAccess, by
        #       default session name will be set to "eZSESSID{siteaccess_hash}" (unique session name per siteaccess)
        #       Further reading on sessions: http://doc.ezplatform.com/en/latest/guide/sessions/
    http_method_override: true
    assets:
        packages:
            ezplatform:
                json_manifest_path: '%kernel.project_dir%/web/assets/ezplatform/build/manifest.json'

