parameters:
    ## Session handler, by default set to file based (instead of ~) in order to be able to use %ezplatform.session.save_path%
    # env: SESSION_HANDLER_ID
    ezplatform.session.handler_id: session.handler.native_file

    env(SESSION_SAVE_PATH): '%kernel.project_dir%/var/sessions/%kernel.environment%'

    # Session save path as used by symfony session handlers (eg. used for dsn with redis)
    ezplatform.session.save_path: '%env(SESSION_SAVE_PATH)%'

    env(SYMFONY_SECRET): ThisEzPlatformTokenIsNotSoSecretChangeIt
    # A secret key that's used to generate certain security-related tokens
    secret: '%env(SYMFONY_SECRET)%'

framework:
    esi: ~
    secret: '%secret%'
    router:
        strict_requirements: ~
    csrf_protection: ~
    form: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        # if handler_id set to null will use default session handler from php.ini
        handler_id: '%ezplatform.session.handler_id%'
        save_path: '%ezplatform.session.save_path%'
        # Note: eZ Platform also allows session name and session cookie configuration to be per SiteAccess, by
        #       default session name will be set to "eZSESSID{siteaccess_hash}" (unique session name per siteaccess)
        #       Further reading on sessions: http://doc.ezplatform.com/en/latest/guide/sessions/
    fragments: ~
    http_method_override: true
    php_errors:
        log: true
