parameters:
    locale_fallback: en

    ## Session handler, by default set to file based (instead of ~) in order to be able to use %ezplatform.session.save_path%
    # env: SESSION_HANDLER_ID
    ezplatform.session.handler_id: session.handler.native_file

    # Session save path as used by symfony session handlers (eg. used for dsn with redis)
    ezplatform.session.save_path: '%env(SESSION_SAVE_PATH)%'

framework:
    esi: true
    fragments: true
    translator: { fallback: '%locale_fallback%' }
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true
    default_locale: '%locale_fallback%'
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        # if handler_id set to null will use default session handler from php.ini
        handler_id: '%ezplatform.session.handler_id%'
        save_path: '%ezplatform.session.save_path%'
        # Note: eZ Platform also allows session name and session cookie configuration to be per SiteAccess, by
        #       default session name will be set to "eZSESSID{siteaccess_hash}" (unique session name per siteaccess)
        #       Further reading on sessions: http://doc.ezplatform.com/en/latest/guide/sessions/
    assets:
        packages:
            ezplatform:
                json_manifest_path: '%kernel.project_dir%/web/assets/ezplatform/build/manifest.json'
    php_errors:
        log: true
