# Webpack Encore Configuration
webpack_encore:
    output_path: "%kernel.project_dir%/public/assets/build"
    builds:
        ezplatform: "%kernel.project_dir%/public/assets/ezplatform/build"
    cache: '%kernel.debug%'
