kernel.rest:
    resource: '@EzPlatformRestBundle/Resources/config/routing.yml'
    prefix: '%ezpublish_rest.path_prefix%'

kernel.rest.options:
    resource: '@EzPlatformRestBundle/Resources/config/routing.yml'
    prefix: '%ezpublish_rest.path_prefix%'
    type: rest_options
