ezplatform_admin_ui:
    resource: '@EzPlatformAdminUiBundle/Resources/config/routing.yml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'

ezplatform_admin_ui_rest:
    resource: '@EzPlatformAdminUiBundle/Resources/config/routing_rest.yml'
    prefix: '%ezpublish_rest.path_prefix%'
