#overblog_graphql:
#  resource: "@OverblogGraphQLBundle/Resources/config/routing/graphql.yml"
#
#overblog_graphql_endpoint:
#  path: /graphql
#  defaults:
#    _controller: Overblog\GraphQLBundle\Controller\GraphController::endpointAction
#    _format: json
