imports:
    - { resource: default_parameters.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: cache_pool/cache.tagaware.filesystem.yml }
    - { resource: env/generic.php }
    - { resource: env/platformsh.php }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    ezpublish_rest.csrf_token_intention: authenticate
