# This file contains defaults for optional parameters, which you can override in parameters.yml
parameters:
    locale_fallback: en

    # A secret key that's used to generate certain security-related tokens
    secret: '%env(SYMFONY_SECRET)%'

    # Setting for mail system, used by SwiftMailer
    mailer_host: '%env(MAILER_HOST)%'
    mailer_user: '%env(MAILER_USER)%'
    mailer_password: '%env(MAILER_PASSWORD)%'



    # Log path, where to store the log files. php://stderr may be used in order to log to standard error
    log_path: '%env(LOG_PATH)%'


    # Cache DSN, see app/config/services/cache.yml for examples:
    cache_dsn: '%env(CACHE_DSN)%'


    # Session save path as used by symfony session handlers (eg. used for dsn with redis)
    ezplatform.session.save_path: '%env(SESSION_SAVE_PATH)%'

    # Recommendation Bundle params
    ez_recommendation.default.yoochoose.customer_id: '%env(RECOMMENDATIONS_CUSTOMER_ID)%'
    ez_recommendation.default.yoochoose.license_key: '%env(RECOMMENDATIONS_LICENSE_KEY)%'
    ez_recommendation.default.server_uri: '%env(PUBLIC_SERVER_URI)%'


    env(LOG_PATH): "%kernel.logs_dir%/%kernel.environment%.log"



    env(RECOMMENDATIONS_CUSTOMER_ID):   ~
    env(RECOMMENDATIONS_LICENSE_KEY):   ~
    env(PUBLIC_SERVER_URI):             ~

    # Compile time handlers
    ## These are defined at compile time, and hence can't be set at runtime using env()
    ## app/config/env/generic.php takes care about letting you set them by env variables

    ## Log type is one of "stream", "error_log" or other types supported by monolog
    # env: LOG_TYPE
    log_type: stream

    ## Mail transport used by SwiftMailer
    # env: MAILER_TRANSPORT
    mailer_transport:  smtp


    ## Session handler, by default set to file based (instead of ~) in order to be able to use %ezplatform.session.save_path%
    # env: SESSION_HANDLER_ID
    ezplatform.session.handler_id: session.handler.native_file

    # Admin siteaccess group name
    admin_group_name: admin_group
